### ISSUE TITLE
Preprocess for MAESTRO dataset

### ISSUE THREAD

**Issue by d223302** [toizzy/tilt-transfer#1]
Hi, I noticed in [this file](https://github.com/toizzy/tilt-transfer/blob/4ba6befcde3cc94735d7d97d83e07aa833a380b1/corpora/raw_to_tokens/music_note.txt), you mentioned that the MAESTRO dataset can be read directly from its downloaded form. The dataset I download from https://magenta.tensorflow.org/datasets/maestro contains only MIDI file, which can't be read as numpy array. But it seams that https://github.com/toizzy/tilt-transfer/blob/4ba6befcde3cc94735d7d97d83e07aa833a380b1/corpora/make_corpus_object.py#L74 only takes input that is loadable for numpy. I guess I'm missing some preprocess steps. Please correct me if I miss anything.

**Comment by toizzy** [comment]
You're right I had forgotten to include the preprocessing code! I added a link in the readme to the colab for doing that.
